### ISSUE TITLE
Why do we need to subtract 0.5 when testing?

### ISSUE THREAD

**Issue by Cat-Guijun** [zhang-xd18/cfnet#1]
Dear sir,
Thanks for your excellent work. 
Why do we need to subtract 0.5 when testing?
When I implement it myself, if there is a negative value, the NMSE calculation is always positive, thank you very much.

**Comment by zhang-xd18** [comment]
Because the output of the network is centered at 0.5 and lies in [0,1], due to the Sigmoid function. However, the values in the real channel should be normalized and centered at 0. So we need to subtract 0.5 when calculating NMSE.
I hope this answers your question. Thank you.
